#!/usr/bin/env python3
"""
Generate bench_sites.rs with a configurable number of synthetic dyndbg descriptors.

Usage:
  python3 gen_synth_sites.py N > bench_sites.rs       # N descriptors
  python3 gen_synth_sites.py 500                       # 500 descriptors (default)

All descriptors share file="bench_sites.rs", module="dyndbg_bench".
Function names are bench_log_N with unique line numbers for each.
"""

import sys

HEADER = r'''// SPDX-License-Identifier: MPL-2.0

// AUTO-GENERATED by gen_synth_sites.py — DO NOT EDIT MANUALLY.
// This file contains {count} benchmark callsites for scalability testing.

macro_rules! gen_bench_logs {{
    ($($name:ident => $msg:literal),* $(,)?) => {{
        $(
            #[inline(never)]
            fn $name() {{
                aster_logger::dyndbg_debug_site!($msg, $msg);
                core::hint::black_box(());
            }}
        )*

        #[allow(non_upper_case_globals)]
        static BENCH_FNS: &[fn()] = &[
            $( $name ),*
        ];

        #[inline(never)]
        pub fn bench_log_batch() {{
            for f in BENCH_FNS {{
                core::hint::black_box(f());
            }}
        }}
    }}
}}

gen_bench_logs! {{
'''

FOOTER = '''}
'''


def main():
    n = int(sys.argv[1]) if len(sys.argv) > 1 else 500

    print(HEADER.format(count=n))

    # Generate N entries, 16 per line for compactness
    entries = []
    for i in range(n):
        entries.append(f"bench_log_{i} => \"bench_{i}\"")

    per_line = 16
    for i in range(0, len(entries), per_line):
        chunk = entries[i:i + per_line]
        line = "    " + ",".join(chunk) + ","
        print(line)

    print(FOOTER)


if __name__ == "__main__":
    main()
