#!/usr/bin/env python3
"""
Generate bench_sites.rs with a configurable number of synthetic dyndbg descriptors.

Usage:
  python3 gen_synth_sites.py N > bench_sites.rs       # N descriptors
  python3 gen_synth_sites.py 500                       # 500 descriptors (default)
  python3 gen_synth_sites.py 500 --line-out LINE_FILE  # also write entry line number

All descriptors share file="bench_sites.rs", module="dyndbg_bench".
Function names are bench_log_N with unique line numbers for each.

The first entry (bench_log_0) always lands on the same line regardless of N,
because the HEADER template has a fixed number of lines.  Use --line-out to
persist that line number for scripts that need it (e.g. index_ablation.sh).
"""

import sys

HEADER = r'''// SPDX-License-Identifier: MPL-2.0

// AUTO-GENERATED by gen_synth_sites.py — DO NOT EDIT MANUALLY.
// This file contains {count} benchmark callsites for scalability testing.

macro_rules! gen_bench_logs {{
    ($($name:ident => $msg:literal),* $(,)?) => {{
        $(
            #[inline(never)]
            fn $name() {{
                aster_logger::dyndbg_debug_site!($msg, $msg);
                core::hint::black_box(());
            }}
        )*

        #[allow(non_upper_case_globals)]
        static BENCH_FNS: &[fn()] = &[
            $( $name ),*
        ];

        #[inline(never)]
        pub fn bench_log_batch() {{
            for f in BENCH_FNS {{
                core::hint::black_box(f());
            }}
        }}
    }}
}}

gen_bench_logs! {{
'''

FOOTER = '''}
'''

# The first dyndbg_debug_site! entry always lands on this line.
# HEADER has N newlines → HEADER occupies N lines.
# print() appends an extra newline (since HEADER already ends with \n).
# So the first entry line = HEADER.count('\n') + 2.
FIRST_ENTRY_LINE = HEADER.count('\n') + 2


def main():
    args = [a for a in sys.argv[1:] if not a.startswith('--line-out')]
    line_out = None
    for i, a in enumerate(sys.argv[1:]):
        if a == '--line-out' and i + 2 < len(sys.argv):
            line_out = sys.argv[i + 2]
            break

    n = int(args[0]) if args else 500

    if line_out:
        with open(line_out, 'w') as f:
            f.write(f"{FIRST_ENTRY_LINE}\n")
        print(f"# wrote bench_log_0 line number ({FIRST_ENTRY_LINE}) to {line_out}", file=sys.stderr)

    print(HEADER.format(count=n))

    # Generate N entries, 16 per line for compactness
    entries = []
    for i in range(n):
        entries.append(f"bench_log_{i} => \"bench_{i}\"")

    per_line = 16
    for i in range(0, len(entries), per_line):
        chunk = entries[i:i + per_line]
        line = "    " + ",".join(chunk) + ","
        print(line)

    print(FOOTER)


if __name__ == "__main__":
    main()
