#!/usr/bin/env python3
"""
Generate bench_sites.rs with a configurable number of synthetic dyndbg descriptors.

Usage:
  python3 gen_synth_sites.py N                        # N descriptors, single module (default)
  python3 gen_synth_sites.py N --modules M            # N descriptors spread over M modules
  python3 gen_synth_sites.py N --modules M --line-out LINE_FILE

Single-module mode (default): all descriptors share file="bench_sites.rs",
module="dyndbg_bench" — `module=dyndbg_bench` matches N/N = 100% of sites.

Multi-module mode (--modules M): descriptors are spread evenly over M inline
`mod bench_m0..bench_m{M-1}` blocks, so `module=bench_m0` matches only the
first module's ~N/M sites (real-kernel-like selectivity; the M/N = 100%
drawback disappears). `module=dyndbg_bench` still matches all sites (the
ancestor segment is present in every path). File and line keys are unchanged.

The first entry (bench_log_0) always lands on the same line regardless of N,
because the header templates have fixed sizes.  Use --line-out to persist that
line number for scripts that need it (e.g. index_ablation.sh).
"""

import sys

HEADER = r'''// SPDX-License-Identifier: MPL-2.0

// AUTO-GENERATED by gen_synth_sites.py — DO NOT EDIT MANUALLY.
// This file contains {count} benchmark callsites for scalability testing.

macro_rules! gen_bench_logs {{
    ($($name:ident => $msg:literal),* $(,)?) => {{
        $(
            #[inline(never)]
            pub fn $name() {{
                aster_logger::dyndbg_debug_site!($msg, $msg);
                core::hint::black_box(());
            }}
        )*

        #[allow(non_upper_case_globals)]
        static BENCH_FNS: &[fn()] = &[
            $( $name ),*
        ];

        #[inline(never)]
        pub fn bench_log_batch() {{
            for f in BENCH_FNS {{
                core::hint::black_box(f());
            }}
        }}
    }}
}}

gen_bench_logs! {{
'''

FOOTER = '''}
'''

# The first dyndbg_debug_site! entry always lands on this line.
# HEADER has N newlines → HEADER occupies N lines.
# print() appends an extra newline (since HEADER already ends with \n).
# So the first entry line = HEADER.count('\n') + 2.
FIRST_ENTRY_LINE = HEADER.count('\n') + 2

MULTI_HEADER = r'''// SPDX-License-Identifier: MPL-2.0

// AUTO-GENERATED by gen_synth_sites.py — DO NOT EDIT MANUALLY.
// This file contains {count} benchmark callsites across {modules} modules
// for scalability testing.

macro_rules! gen_bench_logs {{
    ($($name:ident => $msg:literal),* $(,)?) => {{
        $(
            #[inline(never)]
            pub fn $name() {{
                aster_logger::dyndbg_debug_site!($msg, $msg);
                core::hint::black_box(());
            }}
        )*
    }}
}}
'''


def emit_single(n):
    # Byte-identical to the original generator: print() semantics add one
    # trailing newline after the header (which already ends with '\n') and
    # one after the footer. Keeps FIRST_ENTRY_LINE valid.
    out = HEADER.format(count=n) + "\n"
    entries = [f"bench_log_{i} => \"bench_{i}\"" for i in range(n)]
    per_line = 16
    chunks = []
    for i in range(0, len(entries), per_line):
        chunks.append("    " + ",".join(entries[i:i + per_line]) + ",")
    return out + "\n".join(chunks) + "\n" + FOOTER + "\n"


def emit_multi(n, m):
    """N sites spread evenly over M inline `mod bench_m{i}` blocks.

    Module paths become ...::bench_sites::bench_m{i} — `module=bench_m0`
    matches only the first module's ~N/M sites, so the module selector has
    real-kernel-like selectivity instead of the degenerate N/N = 100%.
    """
    base, rem = divmod(n, m)
    mod_sizes = [base + (1 if i < rem else 0) for i in range(m)]

    out = [MULTI_HEADER.format(count=n, modules=m).rstrip('\n')]
    idx = 0
    for i, size in enumerate(mod_sizes):
        out.append(f"mod bench_m{i} {{")
        out.append("    gen_bench_logs! {")
        for j in range(size):
            out.append(f"        bench_log_{idx} => \"bench_{idx}\",")
            idx += 1
        out.append("    }")
        out.append("}")

    # Aggregate all sites for the existing bench_sites::bench_log_batch()
    # interface (dyndbg_bench.rs calls it unchanged).
    out.append("")
    out.append("#[allow(non_upper_case_globals)]")
    out.append("static BENCH_FNS: &[fn()] = &[")
    idx = 0
    for i, size in enumerate(mod_sizes):
        for j in range(size):
            out.append(f"    bench_m{i}::bench_log_{idx},")
            idx += 1
    out.append("];")
    out.append("")
    out.append("#[inline(never)]")
    out.append("pub fn bench_log_batch() {")
    out.append("    for f in BENCH_FNS {")
    out.append("        core::hint::black_box(f());")
    out.append("    }")
    out.append("}")
    return "\n".join(out) + "\n"


def line_of_first_entry(text):
    """Line number (1-based) of the first `bench_log_0 =>` occurrence."""
    for lineno, line in enumerate(text.split('\n'), start=1):
        if "bench_log_0 =>" in line:
            return lineno
    raise RuntimeError("bench_log_0 entry not found in generated output")


def main():
    argv = sys.argv[1:]
    line_out = None
    modules = None
    positional = []
    i = 0
    while i < len(argv):
        if argv[i] == '--line-out' and i + 1 < len(argv):
            line_out = argv[i + 1]
            i += 2
        elif argv[i] == '--modules' and i + 1 < len(argv):
            modules = int(argv[i + 1])
            i += 2
        else:
            positional.append(argv[i])
            i += 1

    n = int(positional[0]) if positional else 500
    if modules is not None and (modules <= 0 or modules > n):
        sys.stderr.write(f"error: --modules must be in [1, N] (got {modules})\n")
        sys.exit(1)

    if modules is None:
        text = emit_single(n)
        first_line = FIRST_ENTRY_LINE
    else:
        text = emit_multi(n, modules)
        first_line = line_of_first_entry(text)

    if line_out:
        with open(line_out, 'w') as f:
            f.write(f"{first_line}\n")
        print(f"# wrote bench_log_0 line number ({first_line}) to {line_out}",
              file=sys.stderr)

    print(text, end='')


if __name__ == "__main__":
    main()
